import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const roboto = Roboto({ 
  weight:['400'],
  subsets: ["latin"], 
});

export const metadata: Metadata = {
  title: "DriverCalc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body  className={`${roboto.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
